openapi: 3.0.0

info:
  title: nodejs-aws-be
  version: 0.0.1

servers:
  - url: 'https://5j0uel8y5i.execute-api.us-east-1.amazonaws.com/dev'

paths:
  '/products':
    get:
      summary: Returns a list of products.
      responses:
        '200':
          description: A JSON array of Products
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
  '/products/{id}':
    get:
      summary: Returns a Product by Id.
      parameters:
        - name: id
          in: path
          required: true
          description: Product Id.
          schema:
            type: string
            default: 'bb463b8b-b76c-4f6a-9726-65ab5730b69b'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        '404':
          description: Not Found
          content:
            text/html; chartset=utf-8:
              schema:
                type: string

components:
  schemas:
    Product:
      properties:
        id:
          type: string
          description: uuid
        title:
          type: string
          description: Product title
        description:
          type: string
          description: Product description
        count:
          type: number
          description: Available count
        price:
          type: number
          description: Product price
      required:
        - id
        - title
        - description
        - count
        - price